"""Adiciona chunk_id à tabela sources

Revision ID: eeda09f0e52f
Revises: 88b0751b6d42
Create Date: 2026-06-22 13:42:22.010169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeda09f0e52f'
down_revision: Union[str, Sequence[str], None] = '88b0751b6d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('chunk_id', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_sources_chunk_id'), 'sources', ['chunk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_chunk_id'), table_name='sources')
    op.drop_column('sources', 'chunk_id')
    # ### end Alembic commands ###
