"""Adiciona controle de token nas interações

Revision ID: fc9aece76fea
Revises: eeda09f0e52f
Create Date: 2026-07-29 09:58:43.456183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9aece76fea'
down_revision: Union[str, Sequence[str], None] = 'eeda09f0e52f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('total_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'total_tokens')
    # ### end Alembic commands ###
